# Generated by Django 4.2.2 on 2023-07-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivosEletronicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaladeAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('bloco', models.CharField(max_length=100)),
                ('DispositivosEletronicos', models.ManyToManyField(blank=True, to='core.dispositivoseletronicos')),
            ],
        ),
    ]
