# Generated by Django 4.2.2 on 2023-07-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alocacao_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=10)),
                ('horario', models.CharField(choices=[('08:00', '08:00'), ('10:00', '10:00'), ('13:30', '13:30'), ('15:30', '15:30')], max_length=5)),
            ],
        ),
    ]
