# Generated by Django 4.2.2 on 2023-07-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
        ),
    ]
